<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aae010a0b68656c6c6f2e70726f746f1214676f2e6d6963726f2e737276" .
            "2e6772656574657222170a0752657175657374120c0a046e616d65180120" .
            "01280922170a08526573706f6e7365120b0a036d7367180120012809324f" .
            "0a0353617912480a0548656c6c6f121d2e676f2e6d6963726f2e7372762e" .
            "677265657465722e526571756573741a1e2e676f2e6d6963726f2e737276" .
            "2e677265657465722e526573706f6e73652200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

